import { CropId, MonsterType } from './constants';
import type { CropDef, JobDef, LotDef, MonsterDef, NpcDef, QuestDef } from './types';

export const CROPS: Record<CropId, CropDef> = {
  [CropId.Turnip]: {
    id: CropId.Turnip,
    name: 'Turnip',
    daysToGrow: 2,
    sellPrice: 15,
    seedCost: 5,
  },
  [CropId.CoffeeBean]: {
    id: CropId.CoffeeBean,
    name: 'Coffee Bean',
    daysToGrow: 3,
    sellPrice: 30,
    seedCost: 10,
  },
  [CropId.StickyNoteFlower]: {
    id: CropId.StickyNoteFlower,
    name: 'Sticky-Note Flower',
    daysToGrow: 2,
    sellPrice: 20,
    seedCost: 8,
  },
};

export const MONSTERS: Record<MonsterType, MonsterDef> = {
  [MonsterType.TicketTick]: {
    type: MonsterType.TicketTick,
    name: 'Ticket Tick',
    hp: 10,
    speed: 52,
    damage: 3,
    color: 0x26a69a,
    radius: 13,
  },
  [MonsterType.ScopeCreepBat]: {
    type: MonsterType.ScopeCreepBat,
    name: 'Scope-Creep Bat',
    hp: 9,
    speed: 88,
    damage: 4,
    color: 0x7e57c2,
    radius: 12,
  },
  [MonsterType.LegacyBugBeetle]: {
    type: MonsterType.LegacyBugBeetle,
    name: 'Legacy-Bug Beetle',
    hp: 18,
    speed: 36,
    damage: 4,
    color: 0x8d6e63,
    radius: 16,
  },
  [MonsterType.AtticBoss]: {
    type: MonsterType.AtticBoss,
    name: 'The Unscoped Scope',
    hp: 60,
    speed: 52,
    damage: 6,
    color: 0xc62828,
    radius: 28,
  },
};

export const SHARED_BANTER = [
  'ValuePro Valley: where tickets go to become quests.',
  'If you hear attic noises, that is… probably a feature.',
  'Majority sleep votes are how we do agile here.',
  'Bring coffee. Bring a sword. Bring friends.',
  'The firm rep meter is watching. No pressure.',
  'Help Wanted board does not care about your calendar.',
  'Big House restoration: 40% quests, 60% vibes.',
  'Pixel art heals the soul. Ticket ticks do not.',
  'Standup Cafe gossip travels faster than SignalR.',
  'Have you submitted the report yet? Asking for QA.',
];

export const SUPPORT_BANTER = [
  'Queue is green. Do not jinx it.',
  'That bug is reproducible on my machine. Unfortunately.',
  'Customer tone: spicy. Response: professional chaos.',
  'Escalation matrix says: you, then Gabe, then destiny.',
  'I logged it. The ticket tick did not care.',
  'Remote session into a cottage? Absolutely not.',
];

export const RND_BANTER = [
  'Ship it behind a flag. Then another flag.',
  'We can refactor the valley after one more coffee.',
  'If it compiles in the village, it ships.',
  'Telemetry on friendship hearts when?',
  'This map needs better collision… and better snacks.',
  'PR description: "misc valley stuff". Perfect.',
];

export const NPCS: NpcDef[] = [
  // Support — distributed around the office, cafe, and plaza.
  {
    id: 'maillene',
    name: 'Maillene',
    role: 'Support',
    team: 'support',
    x: 12.5 * 32,
    y: 11.2 * 32,
    color: 0xffb74d,
    greetings: [
      'Ticket queue looks calm… for now.',
      'If a pest files a bug, escalate to Gabe.',
      'Coffee run? Standup Cafe is right there.',
      'I already triaged three imaginary tickets today.',
      'Please do not CC the ticket ticks.',
      'Keys are on the Help Wanted board. Do not ask how I know.',
      'Your inspection checklist is my love language.',
      'If the board posts a weird duplex, walk carefully.',
    ],
    lovedGifts: ['lgtm', 'todo_sticky'],
    likedGifts: ['green_ci'],
    hatedGifts: ['legacy_bug'],
    heartQuestAt: 2,
    heartQuestId: 'quest_office_keys',
  },
  {
    id: 'al',
    name: 'Al',
    role: 'Support',
    team: 'support',
    x: 22.5 * 32,
    y: 16 * 32,
    color: 0xffcc80,
    greetings: [
      'Have you tried turning the legacy bug off and on again?',
      'Spare keys are behind the Help Wanted board.',
      'Support energy: high. Big House vibes: haunted.',
      'I wrote a knowledge base article titled “Don’t.”',
      'That bat is in scope. Tragically.',
      'Gift me something from your desk. Receive wisdom. Or at least morale.',
      'If it screams in the attic, capture logs.',
      'I am emotionally prepared for day two tickets.',
    ],
    lovedGifts: ['green_ci', 'lgtm'],
    likedGifts: ['mech_keycap'],
    hatedGifts: ['legacy_bug'],
  },
  {
    id: 'sudhir',
    name: 'Sudhir',
    role: 'Support',
    team: 'support',
    x: 23 * 32,
    y: 11.4 * 32,
    color: 0xffa726,
    greetings: [
      'Repro steps: walk into attic, regret decisions.',
      'Ping me if the job board lies again.',
      'Sticky TODOs are a love language.',
      'I labelled every rock. Still lost.',
      'Can we mark this beetle as “won’t fix”?',
      'Your sword is a valid workaround. Document it.',
      'I have screenshots of the bats. Many screenshots.',
      'Noticeboard first, heroics second.',
    ],
    lovedGifts: ['todo_sticky', 'rubber_duck'],
    likedGifts: ['lgtm'],
    hatedGifts: ['mech_keycap'],
  },
  {
    id: 'david',
    name: 'David',
    role: 'Support',
    team: 'support',
    x: 28.5 * 32,
    y: 12.5 * 32,
    color: 0xff8a65,
    greetings: [
      'Bridge still out. Turnips are… structural, right?',
      'Customer said the bats have scope creep. Accurate.',
      'Take a job, clear the pests, sleep.',
      'I filed the creek under “infra debt”.',
      'Bring two keycaps or bring excuses. Prefer keycaps.',
      'HP low? Bunks are free therapy.',
      'If the report fails validation, blame the beetles.',
      'Firm reputation is just friendship hearts for business.',
    ],
    lovedGifts: ['mech_keycap', 'lgtm'],
    likedGifts: ['green_ci'],
    hatedGifts: ['legacy_bug'],
    heartQuestAt: 2,
    heartQuestId: 'quest_bridge',
  },
  {
    id: 'savi',
    name: 'Savi',
    role: 'Support',
    team: 'support',
    x: 26 * 32,
    y: 14.8 * 32,
    color: 0xf48fb1,
    greetings: [
      'Standup Cafe needs beans before it needs vibes.',
      'I will cheer from the safe side of the door.',
      'Gift me my favourite desk trinket and I will bless your inspection.',
      'I put hearts on the status board. Literally.',
      'If you faint in a cottage, I will send snacks.',
      'Cafe playlist is 70% support memes.',
      'Beans in, reports out. That is the loop.',
      'You look brave. Also slightly under-caffeinated.',
    ],
    lovedGifts: ['lgtm', 'green_ci'],
    likedGifts: ['todo_sticky'],
    hatedGifts: ['legacy_bug'],
    heartQuestAt: 2,
    heartQuestId: 'quest_cafe',
  },
  {
    id: 'gabe',
    name: 'Gabe',
    role: 'Support',
    team: 'support',
    x: 29 * 32,
    y: 10.5 * 32,
    color: 0xef9a9a,
    greetings: [
      'P0 in the attic. Bring friends. Bring a sword.',
      'I escalate monsters for a living.',
      'Legacy bugs hate TODO stickies. Science.',
      'Severity: cute but deadly.',
      'Do not accept attic alone unless you enjoy chaos.',
      'My inbox is a dungeon. The valley matches.',
      'If it is on fire, assign it. If it has wings, FIGHT.',
      'Greenhouse flowers later. Survival first.',
    ],
    lovedGifts: ['todo_sticky', 'lgtm'],
    likedGifts: ['green_ci'],
    hatedGifts: ['mech_keycap'],
    heartQuestAt: 5,
    heartQuestId: 'quest_greenhouse',
  },

  // R&D — distributed through the western clearing and southern path.
  {
    id: 'stewart',
    name: 'Stewart',
    role: 'R&D',
    team: 'rnd',
    x: 8.5 * 32,
    y: 12.4 * 32,
    color: 0x64b5f6,
    greetings: [
      'We should instrument the monster HP bars.',
      'Quests are just tickets with better UI.',
      'Edge deploy, but make it pastoral.',
      'I want dashboards for friendship hearts.',
      'Latency to the cafe is unacceptable.',
      'Can we A/B test the sword swing?',
      'This valley needs better observability… and trees.',
      'Ship the report. Measure the regret later.',
    ],
    lovedGifts: ['green_ci', 'lgtm'],
    likedGifts: ['todo_sticky'],
    hatedGifts: ['legacy_bug'],
  },
  {
    id: 'zach',
    name: 'Zach',
    role: 'R&D',
    team: 'rnd',
    x: 11 * 32,
    y: 14.8 * 32,
    color: 0x4fc3f7,
    greetings: [
      'Is the Big House behind a feature flag?',
      'I refactored the sword swing in my head.',
      'Ship the report. Trust the process.',
      'Hot reload for cottages when?',
      'That path tile is off by one. I can feel it.',
      'Co-op sockets are my cardio.',
      'If combat is unfair, open an issue. Or dodge harder.',
      'I named my branch fix/valley-vibes.',
    ],
    lovedGifts: ['rubber_duck', 'lgtm'],
    likedGifts: ['green_ci', 'mech_keycap'],
    hatedGifts: ['legacy_bug'],
  },
  {
    id: 'kat',
    name: 'Kat',
    role: 'R&D',
    team: 'rnd',
    x: 7 * 32,
    y: 16 * 32,
    color: 0x81d4fa,
    greetings: [
      'Design review: that bat is off-brand.',
      'Hearts UI needs more hearts. Obviously.',
      'Cafe kitchen is a blockers board in disguise.',
      'Please stop putting text on the grass.',
      'The job board wants more parchment energy.',
      'Contrast on those HP bars is a crime.',
      'I sketched a better bunk. In my notes app.',
      'Pixel fonts or nothing. Fight me. Softly.',
    ],
    lovedGifts: ['todo_sticky', 'lgtm'],
    likedGifts: ['mech_keycap'],
    hatedGifts: ['legacy_bug'],
  },
  {
    id: 'rica',
    name: 'Rica',
    role: 'R&D',
    team: 'rnd',
    x: 13 * 32,
    y: 10.5 * 32,
    color: 0x80cbc4,
    greetings: [
      'Okay but what if the valley had better pixel art?',
      'I will PR the greenhouse after one more coffee.',
      'Do not merge the attic boss without review.',
      'I want trees that actually collide. We have those now.',
      'Can we soft-launch the festival ending?',
      'This whole map is a moodboard with monsters.',
      'Gift system > email. Change my mind.',
      'If you find a flat yellow path, scream. Politely.',
    ],
    lovedGifts: ['lgtm', 'todo_sticky'],
    likedGifts: ['green_ci'],
    hatedGifts: ['legacy_bug'],
  },
  {
    id: 'elaine',
    name: 'Elaine',
    role: 'R&D',
    team: 'rnd',
    x: 24 * 32,
    y: 16 * 32,
    color: 0xa5d6a7,
    greetings: [
      'Specs say the bridge needs two turnips. I checked.',
      'QA the job board before you accept anything spicy.',
      'Festival ending needs a ribbon. Filing that.',
      'Acceptance criteria: survive the dodge phase.',
      'I found a flake in the bunk spawn. Fixed in spirit.',
      'Edge cases live in the attic. Literally.',
      'Please reproduce with steps. And coffee.',
      'If hearts drop, that is also a regression.',
    ],
    lovedGifts: ['green_ci', 'mech_keycap'],
    likedGifts: ['lgtm'],
    hatedGifts: ['legacy_bug'],
  },
  {
    id: 'ed',
    name: 'Ed',
    role: 'R&D',
    team: 'rnd',
    x: 32 * 32,
    y: 13.6 * 32,
    color: 0x9fa8da,
    greetings: [
      'Architecture decision: sword first, then report.',
      'The Unscoped Scope is a known antipattern.',
      'Co-op sleep votes are my favourite distributed system.',
      'We need bounded contexts. And bounded beetles.',
      'Event-driven friendship hearts. I am only half joking.',
      'That cottage door is an API with bad docs.',
      'Latency budget: get out of the bullet before it arrives.',
      'I approved the valley design. With comments.',
    ],
    lovedGifts: ['lgtm', 'green_ci'],
    likedGifts: ['todo_sticky'],
    hatedGifts: ['mech_keycap'],
  },
];


export const QUESTS: QuestDef[] = [];

export const LOTS: LotDef[] = [
  { id: 'cottage', name: 'Starter Cottage', x: 4 * 32, y: 6 * 32, w: 4 * 32, h: 4 * 32 },
  { id: 'mortgage_cottage', name: 'Mortgage Cottage', x: 30 * 32, y: 15 * 32, w: 4 * 32, h: 4 * 32 },
  { id: 'weird_duplex', name: 'Weird Duplex', x: 34 * 32, y: 6 * 32, w: 4 * 32, h: 4 * 32 },
  { id: 'gov_bungalow', name: 'Gov Bungalow', x: 1 * 32, y: 16 * 32, w: 4 * 32, h: 4 * 32 },
  { id: 'big_house', name: 'Big House', x: 18 * 32, y: 1 * 32, w: 4 * 32, h: 6 * 32 },
];

export const JOBS: JobDef[] = [
  {
    id: 'job_tutorial',
    title: 'Inspect the Cottage',
    flavour: 'Warm-up fight. One Ticket Tick (flying pest). Clipboard optional.',
    lotId: 'cottage',
    payout: 25,
    reputation: 5,
    monsterCount: 1,
    monsterTypes: [MonsterType.TicketTick],
    isTutorial: true,
  },
  {
    id: 'job_mortgage',
    title: 'Mortgage Cottage Sweep',
    flavour: 'Lender wants a clean report. Bat + beetle disagree.',
    lotId: 'mortgage_cottage',
    payout: 60,
    reputation: 10,
    monsterCount: 3,
    monsterTypes: [MonsterType.ScopeCreepBat, MonsterType.LegacyBugBeetle, MonsterType.TicketTick],
  },
  {
    id: 'job_duplex',
    title: 'Weird Duplex Walkthrough',
    flavour: 'Scope creep and legacy bugs nested in the walls.',
    lotId: 'weird_duplex',
    payout: 80,
    reputation: 15,
    monsterCount: 4,
    monsterTypes: [MonsterType.ScopeCreepBat, MonsterType.LegacyBugBeetle, MonsterType.TicketTick],
  },
  {
    id: 'job_gov',
    title: 'Government Bungalow',
    flavour: 'Forms were filed. So were beetles and ticks.',
    lotId: 'gov_bungalow',
    payout: 90,
    reputation: 15,
    monsterCount: 4,
    monsterTypes: [MonsterType.LegacyBugBeetle, MonsterType.TicketTick, MonsterType.ScopeCreepBat],
  },
  {
    id: 'job_big_foyer',
    title: 'Big House: Foyer',
    flavour: 'First floor inspection. Mixed pests welcome you.',
    lotId: 'big_house',
    payout: 100,
    reputation: 20,
    monsterCount: 4,
    monsterTypes: [MonsterType.TicketTick, MonsterType.LegacyBugBeetle, MonsterType.ScopeCreepBat],
    isBigHouse: true,
    houseFloor: 1,
  },
  {
    id: 'job_big_kitchen',
    title: 'Big House: Kitchen',
    flavour: 'Something is boiling that should not be.',
    lotId: 'big_house',
    payout: 120,
    reputation: 25,
    monsterCount: 4,
    monsterTypes: [MonsterType.LegacyBugBeetle, MonsterType.ScopeCreepBat, MonsterType.TicketTick],
    isBigHouse: true,
    houseFloor: 2,
  },
  {
    id: 'job_big_hall',
    title: 'Big House: Hall',
    flavour: 'Long corridor. Longer backlog.',
    lotId: 'big_house',
    payout: 140,
    reputation: 30,
    monsterCount: 5,
    monsterTypes: [
      MonsterType.TicketTick,
      MonsterType.ScopeCreepBat,
      MonsterType.LegacyBugBeetle,
    ],
    isBigHouse: true,
    houseFloor: 3,
  },
  {
    id: 'job_big_attic',
    title: 'Big House: Attic Boss',
    flavour: 'Final inspection. The Unscoped Scope awaits.',
    lotId: 'big_house',
    payout: 250,
    reputation: 50,
    monsterCount: 1,
    monsterTypes: [MonsterType.AtticBoss],
    isBigHouse: true,
    houseFloor: 4,
  },
];

/**
 * Gift pool — each room randomly stocks 6 of these as hotbar slots.
 * `label` is what the inventory bar shows (kept short enough to fit a slot).
 */
export const GIFT_ITEMS: Record<string, { id: string; name: string; label: string }> = {
  rubber_duck: { id: 'rubber_duck', name: 'Rubber Duck', label: 'DUCK' },
  mech_keycap: { id: 'mech_keycap', name: 'Mech Keycap', label: 'KEYCAP' },
  boba: { id: 'boba', name: 'Boba Tea', label: 'BOBA' },
  pizza_slice: { id: 'pizza_slice', name: 'Pizza Slice', label: 'PIZZA' },
  dev_hoodie: { id: 'dev_hoodie', name: 'Dev Hoodie', label: 'HOODIE' },
  energy_drink: { id: 'energy_drink', name: 'Energy Drink', label: 'ENERGY' },
  blue_glasses: { id: 'blue_glasses', name: 'Blue-Light Glasses', label: 'GLASSES' },
  ergo_mouse: { id: 'ergo_mouse', name: 'Ergo Mouse', label: 'MOUSE' },
  spare_monitor: { id: 'spare_monitor', name: 'Spare Monitor', label: 'MONITOR' },
  usb_stick: { id: 'usb_stick', name: 'Mystery USB', label: 'USB' },
  desk_plant: { id: 'desk_plant', name: 'Desk Plant', label: 'PLANT' },
  noise_phones: { id: 'noise_phones', name: 'Noise-Cancelling Cans', label: 'HEADSET' },
  lava_lamp: { id: 'lava_lamp', name: 'Lava Lamp', label: 'LAMP' },
  legacy_bug: { id: 'legacy_bug', name: 'Legacy Bug', label: 'BUG' },
};

export const GIFT_ITEM_IDS = Object.keys(GIFT_ITEMS);

/** Slots per room hotbar. */
export const GIFT_SLOT_COUNT = 6;

export const MAP = {
  widthTiles: 40,
  heightTiles: 24,
  trees: [
    { x: 0, y: 5 },
    { x: 6, y: 2 },
    { x: 11, y: 5 },
    { x: 28, y: 3 },
    { x: 37, y: 3 },
    { x: 7, y: 19 },
    { x: 13, y: 19 },
    { x: 24, y: 18 },
    { x: 36, y: 20 },
  ],
  /** Help Wanted board sits on open plaza, clear of buildings and NPCs. */
  jobBoard: { x: 20 * 32, y: 14.2 * 32 },
  /** Kept for save compatibility; no longer drawn or interactable. */
  noticeboard: { x: -999, y: -999 },
  office: { x: 16 * 32, y: 6 * 32, w: 96, h: 64 },
  cafe: { x: 24 * 32, y: 7 * 32, w: 80, h: 48 },
  /** Standing spot in front of the cafe — the building itself is solid. */
  cafeCounter: { x: 26 * 32, y: 11.4 * 32 },
  /** Solid town buildings in tile units — drawn client-side, collided server-side. */
  buildings: [
    { id: 'firm_office', name: 'Firm Office', tileX: 15, tileY: 5, tilesW: 4, tilesH: 6, large: true },
    { id: 'standup_cafe', name: 'Standup Cafe', tileX: 24, tileY: 7, tilesW: 4, tilesH: 4, large: false },
  ],
  /** One bunk per co-op slot; beds spawn only for joined players. */
  bedSlots: [
    { x: 2.2 * 32, y: 10.2 * 32 },
    { x: 3.6 * 32, y: 10.2 * 32 },
    { x: 2.2 * 32, y: 11.4 * 32 },
    { x: 3.6 * 32, y: 11.4 * 32 },
  ],
};
