import { CropId, MonsterType } from './constants';
import type { CropDef, JobDef, LotDef, MonsterDef, NpcDef, QuestDef } from './types';

export const CROPS: Record<CropId, CropDef> = {
  [CropId.Turnip]: {
    id: CropId.Turnip,
    name: 'Turnip',
    daysToGrow: 2,
    sellPrice: 15,
    seedCost: 5,
  },
  [CropId.CoffeeBean]: {
    id: CropId.CoffeeBean,
    name: 'Coffee Bean',
    daysToGrow: 3,
    sellPrice: 30,
    seedCost: 10,
  },
  [CropId.StickyNoteFlower]: {
    id: CropId.StickyNoteFlower,
    name: 'Sticky-Note Flower',
    daysToGrow: 2,
    sellPrice: 20,
    seedCost: 8,
  },
};

export const MONSTERS: Record<MonsterType, MonsterDef> = {
  [MonsterType.SpreadsheetSlime]: {
    type: MonsterType.SpreadsheetSlime,
    name: 'Spreadsheet Slime',
    hp: 8,
    speed: 38,
    damage: 2,
    color: 0x66bb6a,
    radius: 14,
  },
  [MonsterType.ScopeCreepBat]: {
    type: MonsterType.ScopeCreepBat,
    name: 'Scope-Creep Bat',
    hp: 6,
    speed: 78,
    damage: 3,
    color: 0x7e57c2,
    radius: 12,
  },
  [MonsterType.LegacyBugBeetle]: {
    type: MonsterType.LegacyBugBeetle,
    name: 'Legacy-Bug Beetle',
    hp: 14,
    speed: 32,
    damage: 3,
    color: 0x8d6e63,
    radius: 16,
  },
  [MonsterType.AtticBoss]: {
    type: MonsterType.AtticBoss,
    name: 'The Unscoped Scope',
    hp: 45,
    speed: 48,
    damage: 5,
    color: 0xc62828,
    radius: 28,
  },
};

export const SHARED_BANTER = [
  'ValuePro Valley: where tickets go to become quests.',
  'If you hear attic noises, that is… probably a feature.',
  'Majority sleep votes are how we do agile here.',
  'Bring coffee. Bring a sword. Bring friends.',
  'The firm rep meter is watching. No pressure.',
  'Help Wanted board does not care about your calendar.',
  'Big House restoration: 40% quests, 60% vibes.',
  'Pixel art heals the soul. Slimes do not.',
  'Standup Cafe gossip travels faster than SignalR.',
  'Have you submitted the report yet? Asking for QA.',
];

export const SUPPORT_BANTER = [
  'Queue is green. Do not jinx it.',
  'That bug is reproducible on my machine. Unfortunately.',
  'Customer tone: spicy. Response: professional chaos.',
  'Escalation matrix says: you, then Gabe, then destiny.',
  'I logged it. The slime did not care.',
  'Remote session into a cottage? Absolutely not.',
];

export const RND_BANTER = [
  'Ship it behind a flag. Then another flag.',
  'We can refactor the valley after one more coffee.',
  'If it compiles in the village, it ships.',
  'Telemetry on friendship hearts when?',
  'This map needs better collision… and better snacks.',
  'PR description: "misc valley stuff". Perfect.',
];

export const NPCS: NpcDef[] = [
  // Support — distributed around the office, cafe, and plaza.
  {
    id: 'maillene',
    name: 'Maillene',
    role: 'Support',
    team: 'support',
    x: 14 * 32,
    y: 12.4 * 32,
    color: 0xffb74d,
    greetings: [
      'Ticket queue looks calm… for now.',
      'If a slime files a bug, escalate to Gabe.',
      'Coffee run? Standup Cafe is right there.',
      'I already triaged three imaginary tickets today.',
      'Please do not CC the Spreadsheet Slime.',
      'Keys are on the noticeboard. Do not ask how I know.',
      'Your inspection checklist is my love language.',
      'If the board posts a weird duplex, walk carefully.',
    ],
    lovedGifts: ['coffee', 'sticky_note_flower'],
    likedGifts: ['coffee_bean'],
    hatedGifts: ['legacy_bug'],
    heartQuestAt: 2,
    heartQuestId: 'quest_office_keys',
  },
  {
    id: 'al',
    name: 'Al',
    role: 'Support',
    team: 'support',
    x: 20.5 * 32,
    y: 13.6 * 32,
    color: 0xffcc80,
    greetings: [
      'Have you tried turning the Spreadsheet Slime off and on again?',
      'Spare keys are on the noticeboard.',
      'Support energy: high. Big House vibes: haunted.',
      'I wrote a knowledge base article titled “Don’t.”',
      'That bat is in scope. Tragically.',
      'Gift coffee. Receive wisdom. Or at least caffeine.',
      'If it screams in the attic, capture logs.',
      'I am emotionally prepared for day two tickets.',
    ],
    lovedGifts: ['coffee_bean', 'coffee'],
    likedGifts: ['turnip'],
    hatedGifts: ['legacy_bug'],
  },
  {
    id: 'sudhir',
    name: 'Sudhir',
    role: 'Support',
    team: 'support',
    x: 23 * 32,
    y: 11.4 * 32,
    color: 0xffa726,
    greetings: [
      'Repro steps: walk into attic, regret decisions.',
      'Ping me if the job board lies again.',
      'Sticky notes are a love language.',
      'I labelled every rock. Still lost.',
      'Can we mark this slime as “won’t fix”?',
      'Your sword is a valid workaround. Document it.',
      'I have screenshots of the bats. Many screenshots.',
      'Noticeboard first, heroics second.',
    ],
    lovedGifts: ['sticky_note_flower'],
    likedGifts: ['coffee'],
    hatedGifts: ['turnip'],
  },
  {
    id: 'david',
    name: 'David',
    role: 'Support',
    team: 'support',
    x: 28.5 * 32,
    y: 12.5 * 32,
    color: 0xff8a65,
    greetings: [
      'Bridge still out. Turnips are… structural, right?',
      'Customer said the bats have scope creep. Accurate.',
      'Take a job, clear the pests, sleep.',
      'I filed the creek under “infra debt”.',
      'Bring two turnips or bring excuses. Prefer turnips.',
      'HP low? Bunks are free therapy.',
      'If the report fails validation, blame the beetles.',
      'Firm reputation is just friendship hearts for business.',
    ],
    lovedGifts: ['turnip', 'coffee'],
    likedGifts: ['coffee_bean'],
    hatedGifts: ['legacy_bug'],
    heartQuestAt: 2,
    heartQuestId: 'quest_bridge',
  },
  {
    id: 'savi',
    name: 'Savi',
    role: 'Support',
    team: 'support',
    x: 26 * 32,
    y: 14.8 * 32,
    color: 0xf48fb1,
    greetings: [
      'Standup Cafe needs beans before it needs vibes.',
      'I will cheer from the safe side of the door.',
      'Gift me coffee and I will bless your inspection.',
      'I put hearts on the status board. Literally.',
      'If you faint in a cottage, I will send snacks.',
      'Cafe playlist is 70% support memes.',
      'Beans in, reports out. That is the loop.',
      'You look brave. Also slightly under-caffeinated.',
    ],
    lovedGifts: ['coffee', 'coffee_bean'],
    likedGifts: ['sticky_note_flower'],
    hatedGifts: ['legacy_bug'],
    heartQuestAt: 2,
    heartQuestId: 'quest_cafe',
  },
  {
    id: 'gabe',
    name: 'Gabe',
    role: 'Support',
    team: 'support',
    x: 29 * 32,
    y: 10.5 * 32,
    color: 0xef9a9a,
    greetings: [
      'P0 in the attic. Bring friends. Bring a sword.',
      'I escalate monsters for a living.',
      'Legacy bugs hate sticky-note flowers. Science.',
      'Severity: cute but deadly.',
      'Do not accept attic alone unless you enjoy chaos.',
      'My inbox is a dungeon. The valley matches.',
      'If it is on fire, assign it. If it is a slime, FIGHT.',
      'Greenhouse flowers later. Survival first.',
    ],
    lovedGifts: ['sticky_note_flower', 'coffee'],
    likedGifts: ['coffee_bean'],
    hatedGifts: ['turnip'],
    heartQuestAt: 5,
    heartQuestId: 'quest_greenhouse',
  },

  // R&D — distributed through the western clearing and southern path.
  {
    id: 'stewart',
    name: 'Stewart',
    role: 'R&D',
    team: 'rnd',
    x: 8.5 * 32,
    y: 12.4 * 32,
    color: 0x64b5f6,
    greetings: [
      'We should instrument the slime HP bars.',
      'Quests are just tickets with better UI.',
      'Edge deploy, but make it pastoral.',
      'I want dashboards for friendship hearts.',
      'Latency to the cafe is unacceptable.',
      'Can we A/B test the sword swing?',
      'This valley needs better observability… and trees.',
      'Ship the report. Measure the regret later.',
    ],
    lovedGifts: ['coffee_bean', 'coffee'],
    likedGifts: ['sticky_note_flower'],
    hatedGifts: ['legacy_bug'],
  },
  {
    id: 'zach',
    name: 'Zach',
    role: 'R&D',
    team: 'rnd',
    x: 11 * 32,
    y: 14.8 * 32,
    color: 0x4fc3f7,
    greetings: [
      'Is the Big House behind a feature flag?',
      'I refactored the sword swing in my head.',
      'Ship the report. Trust the process.',
      'Hot reload for cottages when?',
      'That path tile is off by one. I can feel it.',
      'Co-op sockets are my cardio.',
      'If combat is unfair, open an issue. Or dodge harder.',
      'I named my branch fix/valley-vibes.',
    ],
    lovedGifts: ['turnip', 'coffee'],
    likedGifts: ['coffee_bean'],
    hatedGifts: ['legacy_bug'],
  },
  {
    id: 'kat',
    name: 'Kat',
    role: 'R&D',
    team: 'rnd',
    x: 7 * 32,
    y: 16 * 32,
    color: 0x81d4fa,
    greetings: [
      'Design review: that bat is off-brand.',
      'Hearts UI needs more hearts. Obviously.',
      'Cafe kitchen is a blockers board in disguise.',
      'Please stop putting text on the grass.',
      'The job board wants more parchment energy.',
      'Contrast on those HP bars is a crime.',
      'I sketched a better bunk. In my notes app.',
      'Pixel fonts or nothing. Fight me. Softly.',
    ],
    lovedGifts: ['sticky_note_flower', 'coffee'],
    likedGifts: ['turnip'],
    hatedGifts: ['legacy_bug'],
  },
  {
    id: 'rica',
    name: 'Rica',
    role: 'R&D',
    team: 'rnd',
    x: 13 * 32,
    y: 10.5 * 32,
    color: 0x80cbc4,
    greetings: [
      'Okay but what if the valley had better pixel art?',
      'I will PR the greenhouse after one more coffee.',
      'Do not merge the attic boss without review.',
      'I want trees that actually collide. We have those now.',
      'Can we soft-launch the festival ending?',
      'This whole map is a moodboard with monsters.',
      'Gift system > email. Change my mind.',
      'If you find a flat yellow path, scream. Politely.',
    ],
    lovedGifts: ['coffee', 'sticky_note_flower'],
    likedGifts: ['coffee_bean'],
    hatedGifts: ['legacy_bug'],
  },
  {
    id: 'elaine',
    name: 'Elaine',
    role: 'R&D',
    team: 'rnd',
    x: 24 * 32,
    y: 16 * 32,
    color: 0xa5d6a7,
    greetings: [
      'Specs say the bridge needs two turnips. I checked.',
      'QA the job board before you accept anything spicy.',
      'Festival ending needs a ribbon. Filing that.',
      'Acceptance criteria: survive the dodge phase.',
      'I found a flake in the bunk spawn. Fixed in spirit.',
      'Edge cases live in the attic. Literally.',
      'Please reproduce with steps. And coffee.',
      'If hearts drop, that is also a regression.',
    ],
    lovedGifts: ['coffee_bean', 'turnip'],
    likedGifts: ['coffee'],
    hatedGifts: ['legacy_bug'],
  },
  {
    id: 'ed',
    name: 'Ed',
    role: 'R&D',
    team: 'rnd',
    x: 32 * 32,
    y: 13.6 * 32,
    color: 0x9fa8da,
    greetings: [
      'Architecture decision: sword first, then report.',
      'The Unscoped Scope is a known antipattern.',
      'Co-op sleep votes are my favourite distributed system.',
      'We need bounded contexts. And bounded beetles.',
      'Event-driven friendship hearts. I am only half joking.',
      'That cottage door is an API with bad docs.',
      'Latency budget: get out of the bullet before it arrives.',
      'I approved the valley design. With comments.',
    ],
    lovedGifts: ['coffee', 'coffee_bean'],
    likedGifts: ['sticky_note_flower'],
    hatedGifts: ['turnip'],
  },
];


export const QUESTS: QuestDef[] = [
  {
    id: 'quest_office_keys',
    title: 'Find the Office Keys',
    description: 'Maillene left the spare keys on the noticeboard. Pick them up there.',
    required: true,
    unlocksHouseFloor: 1,
    rewardCoins: 40,
  },
  {
    id: 'quest_bridge',
    title: 'Fix the Creek Bridge',
    description: 'David needs 2 turnips as “timber substitute”. Hand them in at the noticeboard.',
    required: true,
    unlocksHouseFloor: 1,
    rewardCoins: 50,
  },
  {
    id: 'quest_cafe',
    title: 'Reopen the Cafe Kitchen',
    description: 'Deliver coffee beans for Savi so Standup Cafe can reopen.',
    required: true,
    unlocksHouseFloor: 2,
    rewardCoins: 60,
    rewardSeeds: CropId.CoffeeBean,
  },
  {
    id: 'quest_greenhouse',
    title: 'Repair the Greenhouse',
    description: 'Gabe wants sticky-note flowers — hand in 2 at the noticeboard.',
    required: true,
    unlocksHouseFloor: 3,
    rewardCoins: 80,
  },
  {
    id: 'quest_porch_paint',
    title: 'Paint the Porch',
    description: 'Optional: earn 100 firm reputation then spruce up the Big House porch.',
    required: false,
    unlocksHouseFloor: 3,
    rewardCoins: 30,
  },
  {
    id: 'quest_attic_clear',
    title: 'Final Inspection: Attic',
    description: 'Clear the Big House attic boss to reopen ValuePro Valley.',
    required: true,
    unlocksHouseFloor: 4,
    rewardCoins: 200,
  },
];

export const LOTS: LotDef[] = [
  { id: 'cottage', name: 'Starter Cottage', x: 4 * 32, y: 6 * 32, w: 4 * 32, h: 4 * 32 },
  { id: 'mortgage_cottage', name: 'Mortgage Cottage', x: 30 * 32, y: 15 * 32, w: 4 * 32, h: 4 * 32 },
  { id: 'weird_duplex', name: 'Weird Duplex', x: 34 * 32, y: 6 * 32, w: 4 * 32, h: 4 * 32 },
  { id: 'gov_bungalow', name: 'Gov Bungalow', x: 1 * 32, y: 16 * 32, w: 4 * 32, h: 4 * 32 },
  { id: 'big_house', name: 'Big House', x: 18 * 32, y: 1 * 32, w: 4 * 32, h: 6 * 32 },
];

export const JOBS: JobDef[] = [
  {
    id: 'job_tutorial',
    title: 'Inspect the Cottage',
    flavour: 'Tutorial walkthrough. One friendly slime. Clipboard optional.',
    lotId: 'cottage',
    payout: 25,
    reputation: 5,
    monsterCount: 1,
    monsterTypes: [MonsterType.SpreadsheetSlime],
    isTutorial: true,
  },
  {
    id: 'job_mortgage',
    title: 'Mortgage Cottage Sweep',
    flavour: 'Lender wants a clean report. The bats disagree.',
    lotId: 'mortgage_cottage',
    payout: 60,
    reputation: 10,
    monsterCount: 4,
    monsterTypes: [MonsterType.SpreadsheetSlime, MonsterType.ScopeCreepBat],
  },
  {
    id: 'job_duplex',
    title: 'Weird Duplex Walkthrough',
    flavour: 'Scope creep has nested in the walls.',
    lotId: 'weird_duplex',
    payout: 80,
    reputation: 15,
    monsterCount: 5,
    monsterTypes: [MonsterType.ScopeCreepBat, MonsterType.LegacyBugBeetle],
  },
  {
    id: 'job_gov',
    title: 'Government Bungalow',
    flavour: 'Forms were filed. So were beetles.',
    lotId: 'gov_bungalow',
    payout: 90,
    reputation: 15,
    monsterCount: 5,
    monsterTypes: [MonsterType.LegacyBugBeetle, MonsterType.SpreadsheetSlime],
  },
  {
    id: 'job_big_foyer',
    title: 'Big House: Foyer',
    flavour: 'First floor inspection. Mind the slime puddles.',
    lotId: 'big_house',
    payout: 100,
    reputation: 20,
    monsterCount: 6,
    monsterTypes: [MonsterType.SpreadsheetSlime, MonsterType.ScopeCreepBat],
    isBigHouse: true,
    houseFloor: 1,
  },
  {
    id: 'job_big_kitchen',
    title: 'Big House: Kitchen',
    flavour: 'Something is boiling that should not be.',
    lotId: 'big_house',
    payout: 120,
    reputation: 25,
    monsterCount: 6,
    monsterTypes: [MonsterType.LegacyBugBeetle, MonsterType.ScopeCreepBat],
    isBigHouse: true,
    houseFloor: 2,
  },
  {
    id: 'job_big_hall',
    title: 'Big House: Hall',
    flavour: 'Long corridor. Longer backlog.',
    lotId: 'big_house',
    payout: 140,
    reputation: 30,
    monsterCount: 7,
    monsterTypes: [
      MonsterType.SpreadsheetSlime,
      MonsterType.ScopeCreepBat,
      MonsterType.LegacyBugBeetle,
    ],
    isBigHouse: true,
    houseFloor: 3,
  },
  {
    id: 'job_big_attic',
    title: 'Big House: Attic Boss',
    flavour: 'Final inspection. The Unscoped Scope awaits.',
    lotId: 'big_house',
    payout: 250,
    reputation: 50,
    monsterCount: 1,
    monsterTypes: [MonsterType.AtticBoss],
    isBigHouse: true,
    houseFloor: 3,
  },
];

export const GIFT_ITEMS: Record<string, { id: string; name: string }> = {
  coffee: { id: 'coffee', name: 'Coffee' },
  turnip: { id: 'turnip', name: 'Turnip' },
  coffee_bean: { id: 'coffee_bean', name: 'Coffee Bean' },
  sticky_note_flower: { id: 'sticky_note_flower', name: 'Sticky-Note Flower' },
  legacy_bug: { id: 'legacy_bug', name: 'Legacy Bug (do not gift)' },
};

export const MAP = {
  widthTiles: 40,
  heightTiles: 24,
  trees: [
    { x: 0, y: 5 },
    { x: 6, y: 2 },
    { x: 11, y: 5 },
    { x: 28, y: 3 },
    { x: 37, y: 3 },
    { x: 7, y: 19 },
    { x: 13, y: 19 },
    { x: 24, y: 18 },
    { x: 36, y: 20 },
  ],
  office: { x: 16 * 32, y: 6 * 32, w: 96, h: 64 },
  cafe: { x: 24 * 32, y: 7 * 32, w: 80, h: 48 },
  /** Solid town buildings in tile units — drawn client-side, collided server-side. */
  buildings: [
    { id: 'firm_office', name: 'Firm Office', tileX: 15, tileY: 5, tilesW: 4, tilesH: 6, large: true },
    { id: 'standup_cafe', name: 'Standup Cafe', tileX: 24, tileY: 7, tilesW: 4, tilesH: 4, large: false },
  ],
  /** Boards sit on the plaza path so they stay reachable now buildings are solid. */
  noticeboard: { x: 18.5 * 32, y: 12 * 32 },
  jobBoard: { x: 16 * 32, y: 12 * 32 },
  /** One bunk per co-op slot; beds spawn only for joined players. */
  bedSlots: [
    { x: 2.2 * 32, y: 10.2 * 32 },
    { x: 3.6 * 32, y: 10.2 * 32 },
    { x: 2.2 * 32, y: 11.4 * 32 },
    { x: 3.6 * 32, y: 11.4 * 32 },
  ],
};
